[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "MCSimPython"
version = "0.0.1"
authors = [
  { name="Jan-Erik Hygen", email="janereh@stud.ntnu.no" },
]
description = "Python vessel simulation environment"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
]
