#!/usr/bin/env python3
import rospy

from std_msgs.msg import Float64MultiArray
from nav_msgs.msg import Odometry
from messages.msg import Observer_state, Reference


def refCallback(msg):
    pass


def obsCallback(msg):
    pass


if __name__ == '__main__':
    vessel_name = "CSAD"
    rospy.init_node(f"{vessel_name}_fourier_series_controller")
    rospy.loginfo(f"INITIALIZING {vessel_name} FOURIER SERIES CONTROLLER NODE")
    r = rospy.Rate(100)
    dt = 0.01  # Simulation timestep corresponding to sampling frequency of 100 Hz

    # Subscribers

    reference_sub = rospy.Subscriber(
        f"/{vessel_name}/reference", Reference, refCallback)
    obs_sub = rospy.Subscriber(
        f"/{vessel_name}/observer_states", Observer_state, obsCallback)

    # Publishers
    tauCmd_pub = rospy.Publisher(
        f"/{vessel_name}/tau_cmd", Float64MultiArray, queue_size=1)
    # Messages

    while not rospy.is_shutdown():

        r.sleep()

    rospy.spin()
    rospy.shutdown()
