#!/usr/bin/env python3
import rospy

from std_msgs.msg import Float64MultiArray


def tauCmdCallback(msg):
    pass


if __name__ == '__main__':
    vessel_name = "CSAD"
    rospy.init_node(f"{vessel_name}_kf")
    rospy.loginfo(f"INITIALIZING {vessel_name} THRUST ALLOCATION NODE")
    r = rospy.Rate(100)
    dt = 0.01  # Simulation timestep corresponding to sampling frequency of 100 Hz

    # Subscribers
    tauCmd_sub = rospy.Subscriber(
        f"/{vessel_name}/tau_cmd", Float64MultiArray, tauCmdCallback)

    # Publishers
    u_pub = rospy.Publisher(
        f"/{vessel_name}/u", Float64MultiArray, queue_size=1)
    alpha_pub = rospy.Publisher(
        f"/{vessel_name}/alpha", Float64MultiArray, queue_size=1)

    # Messages

    while not rospy.is_shutdown():

        r.sleep()

    rospy.spin()
    rospy.shutdown()
