#!/usr/bin/env python3
import rospy
import numpy as np

import nav_msgs.msg as Odometry
import std_msgs.msg as Float64MultiArray


def uCallback(msg):
    pass


def alphaCallback(msg):
    pass


if __name__ == '__main__':
    vessel_name = "csad"

    rospy.init_node(f"{vessel_name}")
    rospy.loginfo(f"INITIALIZING {vessel_name} SIMULATION NODE")
    r = rospy.Rate(100)
    dt = 0.01  # Simulation timestep corresponding to sampling frequency of 100 Hz

    # Subscribers
    tau_sub = rospy.Subscriber(
        f"/{vessel_name}/u", Float64MultiArray, uCallback, queue_size=1)
    alpha_sub = rospy.Subscriber(
        f"/{vessel_name}/alpha", Float64MultiArray, alphaCallback, queue_size=1)

    # Publishers
    odom_pub = rospy.Publisher(
        f"/qualisys/{vessel_name}/odom", Odometry, queue_size=1)
    tau_pub = rospy.Publisher(
        f"/{vessel_name}/tau", Float64MultiArray, queue_size=1)

    # Messages
    odom_msg = Odometry()
    tau_msg = Float64MultiArray()

    while not rospy.is_shutdown():
        odom_pub.publish(odom_msg)
        tau_pub.publish(tau_msg)

        r.sleep()

    rospy.spin()
    rospy.shutdown()
